version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'myuser'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: ./StockSim/
    command: python StockSim/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/StockSim
    ports:
      - "8000:8000"
    depends_on:
      - db